# -*- mode:toml; -*-

"name"           = "hadoop"
"version"        = "0.0.1"
"maintainer"     = "Adam Stokes <adam.stokes@ubuntu.com>"
"allowed_fields" = ["pig",
                    "tasktracker_http_threads",
                    "mapreduce_reduce_shuffle_parallelcopies",
                    "source",
                    "hadoop_dir_base",
                    "mapred_child_java_opts",
                    "heap"]
"series"         = ["trusty"]

# No recommended fields
# [fields]
