series = "trusty"
timestamp = "Wed, 02 Dec 2015 07:04:07 -0500"
changelog = [ "Automatic conjure build",]
name = "hadoop"
description = " Hadoop is a software platform that lets one easily write and run applications\n that process vast amounts of data."
maintainer = "Adam Stokes <adam.stokes@ubuntu.com>"
summary = "Software platform for processing vast amounts of data"
version = "0.0.1"
[fields.dfs_datanode_max_xcievers]
Default = 4096
Type = "int"
Description = "The number of files that an datanode will serve at any one time.\nAn Hadoop HDFS datanode has an upper bound on the number of files that it\nwill serve at any one time. This defaults to 256 (which is low) in hadoop\n1.x - however this charm increases that to 4096.\n"
[fields.webhdfs]
Default = false
Type = "boolean"
Description = "Hadoop includes a RESTful API over HTTP to HDFS.  Setting this flag\nto True enables this part of the HDFS service.\n"
[fields.heap]
Default = 1024
Type = "int"
Description = "The maximum heap size in MB to allocate for daemons processes within the\nservice units managed by this charm.\n.\nThe recommended configurations vary based on role and the amount of\nraw disk storage available in the hadoop cluster:\n.\n * NameNode: 1GB of heap for every 100TB of raw data stored.\n * SecondaryNameNode: Must be paired with the NameNode.\n * JobTracker: 2GB.\n * DataNode: 1GB.\n * TaskTracker: 1GB.\n.\nThe above recommendations are taken from HBase: The Definitive Guide by\nLars George.\n.\nObviously you need to ensure that the servers supporting each service unit\nhave sufficient memory to accomodate this setting - it should be no more\nthan 75% of the total memory in the system excluding swap.\n.\nIf you are also mixing MapReduce and DFS roles on the same units you need to\ntake this into account as well (see README for more details).\n"
[fields.dfs_namenode_handler_count]
Default = 10
Type = "int"
Description = "The number of server threads for the namenode.  Increase this in larger\ndeployments to ensure the namenode can cope with the number of datanodes\nthat it has to deal with.\n"
[fields.source]
Default = "stable"
Type = "string"
Description = "Location and packages to install hadoop:\n.\n * dev:     Install using the hadoop packages from\n            ppa:hadoop-ubuntu/dev.\n * testing: Install using the hadoop packages from\n            ppa:hadoop-ubuntu/testing.\n * stable:  Install using the hadoop packages from\n            ppa:hadoop-ubuntu/stable.\n.\nThe packages provided in the hadoop-ubuntu team PPA's are based\ndirectly on upstream hadoop releases but are not fully built from\nsource.\n"
[fields.mapreduce_reduce_shuffle_parallelcopies]
Default = 5
Type = "int"
Description = "The default number of parallel transfers run by reduce during the\ncopy(shuffle) phase.\n"
[fields.dfs_block_size]
Default = 134217728
Type = "int"
Description = "The default block size for new files (default to 64MB).  Increase this in\nlarger deployments for better large data set performance.\n"
[fields.mapreduce_task_io_sort_factor]
Default = 10
Type = "int"
Description = "More streams merged at once while sorting files.. This\ndetermines the number of open file handles.\n"
[fields.mapred_job_tracker_handler_count]
Default = 10
Type = "int"
Description = "The number of server threads for the JobTracker. This should be roughly\n4% of the number of tasktracker nodes.\n"
[fields.hadoop_dir_base]
Default = "/usr/local/hadoop/data"
Type = "string"
Description = "The directory under which all other hadoop data is stored.  Use this\nto take advantage of extra storage that might be avaliable.\n.\nYou can change this in a running deployment but all existing data in\nHDFS will be inaccessible; you can of course switch it back if you\ndo this by mistake.\n"
[fields.dfs_heartbeat_interval]
Default = 3
Type = "int"
Description = "Determines datanode heartbeat interval in seconds.\n"
[fields.dfs_namenode_heartbeat_recheck_interval]
Default = 300000
Type = "int"
Description = "Determines datanode recheck heartbeat interval in milliseconds\nIt is used to calculate the final tineout value for namenode. Calcultion process is    \nas follow: 10.30 minutes = 2 x (dfs.namenode.heartbeat.recheck-interval=5*60*1000)\n                           + 10 * 1000 * (dfs.heartbeat.interval=3)\n"
[fields.yarn_nodemanager_aux-services_mapreduce_shuffle_class]
Default = "org.apache.hadoop.mapred.ShuffleHandler"
Type = "string"
Description = "Shuffle service that needs to be set for Map Reduce applications.\n"
[fields.mapreduce_task_io_sort_mb]
Default = 100
Type = "int"
Description = "Higher memory-limit while sorting data for efficiency..\n"
[fields.pig]
Default = false
Type = "boolean"
Description = "To install Apache Pig on all service units alongside Hadoop set this\nconfiguration to 'True'.\n.\nApache Pig is a platform for analyzing large data sets that consists\nof a high-level language for expressing data analysis programs, coupled\nwith infrastructure for evaluating these programs. The salient property\nof Pig programs is that their structure is amenable to substantial\nparallelization, which in turns enables them to handle very large data\nsets.\n"
[fields.yarn_nodemanager_aux-services]
Default = "mapreduce_shuffle"
Type = "string"
Description = "Shuffle service that needs to be set for Map Reduce applications.\n"
[fields.mapreduce_framework_name]
Default = "yarn"
Type = "string"
Description = "Execution framework set to Hadoop YARN.** DO NOT CHANGE **\n"
[fields.mapred_child_java_opts]
Default = "-Xmx200m"
Type = "string"
Description = "Java opts for the task tracker child processes. The following symbol,\nif present, will be interpolated: @taskid@ is replaced by current TaskID.\nAny other occurrences of '@' will go unchanged. For example, to enable\nverbose gc logging to a file named for the taskid in /tmp and to set\nthe heap maximum to be a gigabyte, pass a 'value' of:\n.\n  -Xmx1024m -verbose:gc -Xloggc:/tmp/@taskid@.gc\n.\nThe configuration variable mapred.child.ulimit can be used to control\nthe maximum virtual memory of the child processes.\n"
[fields.io_file_buffer_size]
Default = 4096
Type = "int"
Description = "The size of buffer for use in sequence files. The size of this buffer should\nprobably be a multiple of hardware page size (4096 on Intel x86), and it\ndetermines how much data is buffered during read and write operations.\n"
[fields.dfs_replication]
Default = 1
Type = "int"
Description = "Default block replication. The actual number of replications can be specified when\nthe file is created. The default is used if replication is not specified in create time\n"
[fields.tasktracker_http_threads]
Default = 40
Type = "int"
Description = "The number of worker threads that for the http server. This is used for\nmap output fetching.\n"
[fields.hbase]
Default = false
Type = "boolean"
Description = "Setting this configuration parameter to 'True' configures HDFS for\nuse with HBase including turning on 'append' mode which is not\ndesirable in all deployment scenarios.\n"
